# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(549, 432)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalFrame = QtWidgets.QFrame(Dialog)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.start_button = QtWidgets.QPushButton(self.horizontalFrame)
        self.start_button.setObjectName("start_button")
        self.horizontalLayout.addWidget(self.start_button)
        self.stop_button = QtWidgets.QPushButton(self.horizontalFrame)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout.addWidget(self.stop_button)
        self.gridLayout.addWidget(self.horizontalFrame, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.what_iface_sniff = QtWidgets.QLineEdit(Dialog)
        self.what_iface_sniff.setObjectName("what_iface_sniff")
        self.horizontalLayout_2.addWidget(self.what_iface_sniff)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.snifftable = QtWidgets.QTableWidget(Dialog)
        self.snifftable.setObjectName("snifftable")
        self.snifftable.setColumnCount(4)
        self.snifftable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.snifftable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.snifftable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.snifftable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.snifftable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.snifftable.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.snifftable)
        self.infotable = QtWidgets.QTableWidget(Dialog)
        self.infotable.setObjectName("infotable")
        self.infotable.setColumnCount(0)
        self.infotable.setRowCount(0)
        self.verticalLayout.addWidget(self.infotable)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Анализ трафика"))
        self.start_button.setText(_translate("Dialog", "Старт"))
        self.stop_button.setText(_translate("Dialog", "Стоп"))
        self.label.setText(_translate("Dialog", "Исследуемый интерфейс"))
        item = self.snifftable.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.snifftable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Source"))
        item = self.snifftable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Destination"))
        item = self.snifftable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Protocol"))
        item = self.snifftable.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Length"))
